name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
      - uses: actions/checkout@v4
      - run: mvn clean
      - run: mvn compile
      - run: mvn test
      

      
